// currencyCountries.js
// Currency code, full name and the country/s where each currency is used
export const currencyCountries = [
    { code: 'AED', name: 'UAE Dirham', countries: ['United Arab Emirates'] },
    { code: 'AUD', name: 'Australian Dollar', countries: ['Australia'] },
    { code: 'BRL', name: 'Brazilian Real', countries: ['Brazil'] },
    { code: 'CAD', name: 'Canadian Dollar', countries: ['Canada'] },
    { code: 'CHF', name: 'Swiss Franc', countries: ['Switzerland', 'Liechtenstein'] },
    { code: 'CNY', name: 'Chinese Yuan', countries: ['China'] },
    { code: 'CZK', name: 'Czech Koruna', countries: ['Czech Republic'] },
    { code: 'DKK', name: 'Danish Krone', countries: ['Denmark', 'Greenland', 'Faroe Islands'] },
    { code: 'EGP', name: 'Egyptian Pound', countries: ['Egypt'] },
    { code: 'EUR', name: 'Euro', countries: ['Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'and other Eurozone countries'] },
    { code: 'GBP', name: 'British Pound', countries: ['United Kingdom'] },
    { code: 'HKD', name: 'Hong Kong Dollar', countries: ['Hong Kong'] },
    { code: 'HUF', name: 'Hungarian Forint', countries: ['Hungary'] },
    { code: 'IDR', name: 'Indonesian Rupiah', countries: ['Indonesia'] },
    { code: 'ILS', name: 'Israeli New Shekel', countries: ['Israel'] },
    { code: 'INR', name: 'Indian Rupee', countries: ['India'] },
    { code: 'JPY', name: 'Japanese Yen', countries: ['Japan'] },
    { code: 'KRW', name: 'South Korean Won', countries: ['South Korea'] },
    { code: 'MXN', name: 'Mexican Peso', countries: ['Mexico'] },
    { code: 'MYR', name: 'Malaysian Ringgit', countries: ['Malaysia'] },
    { code: 'NGN', name: 'Nigerian Naira', countries: ['Nigeria'] },
    { code: 'NOK', name: 'Norwegian Krone', countries: ['Norway'] },
    { code: 'NZD', name: 'New Zealand Dollar', countries: ['New Zealand'] },
    { code: 'PHP', name: 'Philippine Peso', countries: ['Philippines'] },
    { code: 'PKR', name: 'Pakistani Rupee', countries: ['Pakistan'] },
    { code: 'PLN', name: 'Polish Zloty', countries: ['Poland'] },
    { code: 'SAR', name: 'Saudi Riyal', countries: ['Saudi Arabia'] },
    { code: 'SEK', name: 'Swedish Krona', countries: ['Sweden'] },
    { code: 'SGD', name: 'Singapore Dollar', countries: ['Singapore'] },
    { code: 'THB', name: 'Thai Baht', countries: ['Thailand'] },
    { code: 'TRY', name: 'Turkish Lira', countries: ['Turkey'] },
    { code: 'TWD', name: 'New Taiwan Dollar', countries: ['Taiwan'] },
    { code: 'UAH', name: 'Ukrainian Hryvnia', countries: ['Ukraine'] },
    { code: 'USD', name: 'US Dollar', countries: ['United States', 'Ecuador', 'El Salvador'] },
    { code: 'ZAR', name: 'South African Rand', countries: ['South Africa', 'Lesotho', 'Namibia'] },
];
